# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant'
  #for nfs do: apt-get install nfs-kernel-server

  # server.
  # `vagrant up server`
  config.vm.define "server" do |server|
     server.vm.hostname = "server"
     server.vm.box = "file://builds/virtualbox-centos7.box"
     server.vm.network :private_network, ip: "192.168.56.101"
  #   server.vm.provision "shell", path: "haproxy.sh"
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

  end
  # client
  # `vagrant up client`
  config.vm.define "web1" do |web1|
     web1.vm.hostname = "web1.dev"
     web1.vm.box = "file://builds/virtualbox-centos7.box"
     web1.vm.network :private_network, ip: "192.168.56.105"

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

  end
# client
  # `vagrant up client`
  config.vm.define "web2" do |web2|
     web2.vm.hostname = "web2.dev"
     web2.vm.box = "file://builds/virtualbox-centos7.box"
     web2.vm.network :private_network, ip: "192.168.56.110"

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

  end
    
# config.vm.provision "shell", path: "scenario.sh"
end
