# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'nfs'
  #for nfs do: apt-get install nfs-kernel-server


  # VMware Fusion.
  # `vagrant up vmware --provider=vmware_fusion`
  #config.vm.define "vmware" do |vmware|
  #  vmware.vm.hostname = "centos7-vmware"
  #  vmware.vm.box = "file://builds/vmware-centos7.box"
  #  vmware.vm.network :private_network, ip: "192.168.3.2"

  #  config.vm.provider :vmware_fusion do |v, override|
  #    v.gui = false
  #    v.vmx["memsize"] = 1024
  #    v.vmx["numvcpus"] = 1
  #  end

  #  config.vm.provision "shell", inline: "echo Hello, World"
  #end

  # MySql.
  # `vagrant up mysql --provider=virtualbox`
  config.vm.define "mysql" do |mysql|
     mysql.vm.hostname = "mysql.dev"
     mysql.vm.box = "file://builds/MySQL.box"
     mysql.vm.network :private_network, ip: "192.168.56.200"
  #  mysql.vm.provision "shell", path: "scenario_MySql.sh"
    config.vm.provider :mysql do |v|
      v.gui = true
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  # web.
  # `vagrant up web --provider=virtualbox`
  config.vm.define "web" do |web|
     web.vm.hostname = "app.dev"
     web.vm.box = "file://builds/Tomcat.box"
     web.vm.network :private_network, ip: "192.168.56.210"
  #  web.vm.provision "shell", path: "scenario_Tomcat.sh"
    config.vm.provider :web do |v|
      v.gui = true
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
  
  # Jenkins
  # `vagrant up Jenkins --provider=virtualbox`
  config.vm.define "jenkins" do |jenkins|
     jenkins.vm.hostname = "jenkins.dev"
     jenkins.vm.box = "file://builds/Jenkins.box"
     jenkins.vm.network :private_network, ip: "192.168.56.220"
  #  jenkins.vm.provision "shell", path: "scenario_jenkins.sh"
    config.vm.provider :jenkins do |v|
      v.gui = true
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"] 
    end
  end
  
  # GitLab Server.
  # `vagrant up virtualbox --provider=virtualbox`
  config.vm.define "virtualbox" do |virtualbox|
     virtualbox.vm.hostname = "giitlab.dev.com"
     virtualbox.vm.box = "file://builds/virtualbox-centos7.box"
     virtualbox.vm.network :private_network, ip: "192.168.56.223"
  #  virtualbox.vm.provision "shell", path: "scenario.sh"
    config.vm.provider :virtualbox do |v|
      v.gui = true
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]  
    end
  end  
# config.vm.provision "shell", path: "scenario.sh"
end
